### ISSUE TITLE
Possibility to style checkboxes

### ISSUE THREAD

**Issue by pxcfh** [Itvisors/mendix-AutocompleteMultiselect#2]
Hi,

I took a look at the multiselects today and was wondering whether it is possible to style the checkboxes according to my companies corporate design?

The pinkish color is rather intrusive and doesn't fit our color scheme at all.

I hope there is a way and I was just unable to find it or use it properly.

Kind regards

**Comment by jeuhen** [comment]
Hi,

Good to hear that you want to use this widget. I think you can change the color of the checkboxes with some styling.
Have you already tried to change the color with some css? You can change the color of this class: .MuiCheckbox-colorSecondary.Mui-checked

I hope this works for you.

Kind regards

**Comment by pxcfh** [comment]
Hi,

thanks for your fast reply!

I've talked this over with my team and we have additional styling needs. 
Besides the checkboxes we're looking for styling the dropdown menu itself, meaning the font-size and the spacings especially.
We weren't able to find the proper css class for this. Do you know which one it is or if it exists?

In the end we're looking to achieve something like this:
![grafik](https://user-images.githubusercontent.com/79860917/110446504-8bf30300-80bf-11eb-8e41-23fdd414c65e.png)

Would that be possible?

Kind regards

**Comment by jeuhen** [comment]
You can change the font-size e.g. with the class .MuiAutocomplete-listbox
Note that you can freeze your debugger when the dropdown is open (in chrome -> open console, open the dropdown and hover over, press f8), hope this helps

**Comment by jeuhen** [comment]
I assume your request is solved? If not, please let me know. I will close the issue.
