### ISSUE TITLE
Widget is not refreshed/reloaded when using it in a 'listen to' context

### ISSUE THREAD

**Issue by Narev** [Itvisors/mendix-AutocompleteMultiselect#5]
I have a filter on my page that is residing in a listen-to dataview that listens to a list view. When switching between the different entries in the listview the autocomplete widget is not refreshed correctly and keeps on displaying the values of the previous selected entry

**Comment by Narev** [comment]
After reviewing the code a bit more, it seems that using this widget as a reference set selector is more tedious than i thought. Since it uses the response attribute as input for its selected tags to load, which means that if the association changes from else where you also need to update the response attribute. Another issue is that currently the already selected values are not loaded initially.

**Comment by jeuhen** [comment]
Hi Narev,
Indeed you need to set the refresh attribute to load the new defaults and you need to make sure these are set.
Perhaps you can use a on click, such that you can control what is shown?  
The datasource should be refreshed when refreshing the context object.
