### ISSUE TITLE
Custom search in single selection mode

### ISSUE THREAD

**Issue by sergiuszwoznicki** [Itvisors/mendix-AutocompleteMultiselect#6]
Hi,

An error is thrown if using custom search in single selection mode in this line:
https://github.com/Itvisors/mendix-AutocompleteMultiselect/blob/main/src/AutocompleteMultiselect.jsx#L65

as this.optionsSelected is not an array (but a null) in this case - because of logic from this line:
https://github.com/Itvisors/mendix-AutocompleteMultiselect/blob/main/src/AutocompleteMultiselect.jsx#L59

and hence calling .filter() on it triggers an error.

Repro steps:

- Open the test project
- Go to any custom search widget, e.g. on this page: Widget_DSAttribute_CustomSearchMin3Chars
- Change widget setting: General tab > Multi-select from Yes to No
- Run the app, go to the related widget page
- It shows "Cannot render" error

Fix:

Change https://github.com/Itvisors/mendix-AutocompleteMultiselect/blob/main/src/AutocompleteMultiselect.jsx#L65 into:
```
                            const optionsSelectedAsArray = this.props.multiple
                                ? this.optionsSelected
                                : this.optionsSelected === null ? [] : [this.optionsSelected];
                            const optionsSelectedNotInList = optionsSelectedAsArray.filter(...
```

**Comment by jeuhen** [comment]
Hi,

Thanks for your feedback and solution. I just released a new version. 
Please let me know if something is not working :)

**Comment by sergiuszwoznicki** [comment]
Hi, thanks for your update. Verified: it works well (also with another issue we've found later with default options - fixed by you in line https://github.com/Itvisors/mendix-AutocompleteMultiselect/blob/main/src/AutocompleteMultiselect.jsx#L233).
