### ISSUE TITLE
Only possible to add 1 option at the time to the list of selected items

### ISSUE THREAD

**Issue by TimvanSteenbergen** [Itvisors/mendix-AutocompleteMultiselect#8]
Got the setting 'General -> Multi-select' set to 'yes', and I can add multiple options (values), but only one at the time. The [screenshot](https://appstore.home.mendix.com/logo/image?id=482405&changeddate=1698410111713&token=owlSDlIsJqcZ7GQ8) in the tab 'Documentation' suggests that you can select two options at once. 
Hm, I also got the setting 'Behavior -> Filter selected options' set to yes. When I set it to no, only then do I get the same as in the image. 

So, this is not an issue, but a feature-request:
Please add the option to select multiple dropdown-values at the same time. As opposed to like it is now: Type something, select one, type something, select another, etc

**Comment by jeuhen** [comment]
Hi Tim,
Thanks for your feedback! Do you mean that the search value disappears after you select an option or that the dropdown will close? For the second one there is also an option 'No close on select', does this help? 
Otherwise I have to take a look at it :)

**Comment by TimvanSteenbergen** [comment]
Awesome! I missed this option, set it to true and love the way that it is behaving. Gone take some credits and tell my PO that I fixed it :-)

**Comment by TimvanSteenbergen** [comment]
.

**Comment by TimvanSteenbergen** [comment]
O, only one thing: now, after having selected one option, the dropdown stays open, but the dropdown list now shows all values. 
So if at first, with the dropdown still closed, I start typing, then the dropdown opens and contains only the options that match my typed text. As soon as I select one, then the dropdown shows all options. Can it be improved to make the widget keeping filter on typed text?

**Comment by jeuhen** [comment]
Good one, I added this to my list for future improvements. However I cannot pick this up in the next weeks, hope that is no problem?
