### ISSUE TITLE
No close on select not working

### ISSUE THREAD

**Issue by kwSiemens** [Itvisors/mendix-AutocompleteMultiselect#9]
Using the Autocomplete Multiselect Widget, when using the Behaviour no close on select the selection closes after a second value has been selected. Expected it to stay open till manually closed.

**Comment by jeuhen** [comment]
Hi, can you elaborate on this? I cannot reproduce this issue. If I use no close on select, the dropdown remains open until you click outside or the close button. Can you also reproduce this in the test project in this github (test folder)?
